### ISSUE TITLE
Fetch data from newly added static URL

### ISSUE THREAD

**Issue by stekhn** [yetzt/node-dataunwrapper#3]
For new charts, Datawrapper is no longer storing the data within the script tag. Instead, the data for each chart is stored in a dedicated file which can be addressed using a static URL. Example: <https://datawrapper.dwcdn.net/ovyiI/210/dataset.csv>

This is quite convenient, but you need to know the current last version of the chart. I haven't found a way of accessing the dataset without explicitly setting the version number. 

Excerpt from the charts metadata in the script tag:

```json
{
  "chart": {
    "id": "ovyiI",
    "publicUrl": "https://datawrapper.dwcdn.net/ovyiI/209/",
    "publicVersion": 209
  },
  "assets": {
    "dataset.csv": {
      "url": "dataset.csv"
    }
  },
  "externalDataUrl": "static.dwcdn.net/data"
}
```

**Comment by yetzt** [comment]
i'll look into it

**Comment by yetzt** [comment]
implemented. thanks for pointing this out.
